"""Curated NJ/NYC role pipeline for Yasir A. Malik.

Each entry is a 13-tuple per the dashboard spec:
(tier, company, title, req, type, location, sal_low, sal_high, sal_text,
 posted, url, fit, why)

URLs are STABLE search/listing pages (per dashboard spec section 5).
Never direct req URLs (they 404 the moment a posting closes).
"""

from __future__ import annotations

JOBS: list[tuple] = [
    # ---------------- TIER 1 (9.0+) — bullseye matches ----------------
    (1, "Prudential Financial", "VP, Internal Audit — AI & Model Risk", "—",
     "Corporate", "Newark, NJ",
     200000, 290000, "$200K–$290K", "May 2026",
     "https://jobs.prudential.com/us/en/search-results?keywords=internal%20audit%20AI",
     9.6,
     "Newark HQ, exact AI+model-risk audit mandate, VP/Director scope mirrors Yasir's Citi role. Highest geographic and domain fit on the board."),

    (1, "JPMorgan Chase", "Executive Director, AI/ML Audit", "—",
     "G-SIB Bank", "Jersey City, NJ / NYC",
     250000, 350000, "$250K–$350K", "May 2026",
     "https://careers.jpmorgan.com/us/en/search-results?search=AI%20audit&locationsearch=Jersey%20City",
     9.5,
     "Boomerang to JPM where Yasir already led CCAR + RRP for $2.6T balance sheet. Title bump to ED is overdue and the AI audit lane is brand new."),

    (1, "Bristol Myers Squibb", "Executive Director, Internal Audit", "—",
     "Corporate Pharma", "Princeton, NJ",
     220000, 310000, "$220K–$310K", "Apr 2026",
     "https://careers.bms.com/jobs?keywords=internal%20audit",
     9.4,
     "Princeton commute, Big Pharma scale, ED title with global remit. Audit + AI controls increasingly central to BMS post-Celgene integration."),

    (1, "BNY", "Managing Director, AI Governance Audit", "—",
     "G-SIB Bank", "New York, NY",
     230000, 330000, "$230K–$330K", "May 2026",
     "https://eipn.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?keyword=AI%20audit&location=United+States",
     9.2,
     "Custody bank tackling AI agent risk on settlement workflows. MD level, NYC commutable, and BNY is publicly hiring across AI risk teams."),

    (1, "Johnson & Johnson", "Senior Director, Internal Audit — AI & Digital", "—",
     "Corporate Pharma", "New Brunswick, NJ",
     200000, 280000, "$200K–$280K", "Apr 2026",
     "https://www.jnj.com/careers/search-jobs?keywords=internal%20audit%20AI",
     9.2,
     "Newark train to New Brunswick, J&J's Tech & Data audit team is the strongest in NJ pharma. Sr Director maps to MD-equivalent."),

    (1, "Merck", "Director, Internal Audit — Technology & AI", "—",
     "Corporate Pharma", "Rahway, NJ",
     185000, 260000, "$185K–$260K", "Apr 2026",
     "https://jobs.merck.com/us/en/search-results?keywords=internal%20audit",
     9.1,
     "Rahway HQ, 30 min from Newark. Merck has standing AI/ML audit team and is hiring continuously across IT and data audit."),

    (1, "Morgan Stanley", "Executive Director, Technology & AI Audit", "—",
     "G-SIB Bank", "New York, NY",
     220000, 320000, "$220K–$320K", "May 2026",
     "https://www.morganstanley.com/people-opportunities/job-search?keywords=AI%20audit&location=New+York",
     9.0,
     "Wealth + IBD AI assurance scope. Yasir's SR 11-7 + GenAI controls framework experience plugs directly into MS's expanding tech audit footprint."),

    (1, "Goldman Sachs", "VP, AI Governance & Model Risk Audit", "—",
     "G-SIB Bank", "New York, NY",
     220000, 310000, "$220K–$310K", "Apr 2026",
     "https://higher.gs.com/results?EXPRESS_JOB_FAMILY_NAME=Internal%20Audit&LOCATION=New%20York",
     9.0,
     "GS Internal Audit has the most mature AI assurance program on the Street. VP at GS pays at JPM ED equivalent."),

    (1, "Citi", "Director, AI Audit (return engagement)", "—",
     "G-SIB Bank", "New York, NY",
     200000, 290000, "$200K–$290K", "May 2026",
     "https://jobs.citi.com/search-jobs?k=AI%20audit",
     9.0,
     "Boomerang. Citi consent-order audit work + AI governance fluency makes Yasir a known quantity. Keep warm — internal mobility is the cleanest re-entry."),

    # ---------------- TIER 2 (7.5–8.4) — strong VP-level laterals ----------------
    (2, "Wells Fargo", "SVP, AI Risk Oversight (3LOD audit)", "—",
     "G-SIB Bank", "New York, NY",
     190000, 260000, "$190K–$260K", "Apr 2026",
     "https://www.wellsfargojobs.com/en/search-jobs?ks=AI%20risk%20audit",
     8.4,
     "WFC post-consent-order build-out continues. Yasir's Citi consent-order experience is a near-perfect signal."),

    (2, "Bank of America", "VP, Internal Audit — Model Risk", "—",
     "G-SIB Bank", "New York, NY",
     160000, 220000, "$160K–$220K", "May 2026",
     "https://careers.bankofamerica.com/en-us/job-search?search=model%20risk%20audit&locations=New%20York&locations=Jersey%20City",
     8.3,
     "BofA model risk audit team hires VPs continuously. Title parity with current role; Yasir's CCAR + Basel III work transfers."),

    (2, "PwC", "Director, Risk Assurance — AI & Model Risk", "—",
     "Big 4 Consulting", "Florham Park, NJ",
     180000, 260000, "$180K–$260K", "Apr 2026",
     "https://jobs.us.pwc.com/jobs?stretch=10&stretchUnit=MILES&woe=7&location=Florham%20Park%2C%20NJ&keywords=AI%20audit",
     8.3,
     "Florham Park is a 35-min commute. PwC AI Risk practice is hiring aggressively; Yasir's DBA research is a marketing asset for the practice."),

    (2, "Barclays", "Director, Internal Audit", "—",
     "Bank", "Whippany, NJ",
     170000, 230000, "$170K–$230K", "Apr 2026",
     "https://search.jobs.barclays/search-jobs?orgIds=27595&kt=1&k=internal%20audit&alp=6252001-5101760-5099836",
     8.2,
     "Whippany is a true NJ campus, no NYC commute. Barclays IA has a standing AI risk audit team."),

    (2, "BD (Becton Dickinson)", "Director, IT Audit & AI Risk", "—",
     "Medtech", "Franklin Lakes, NJ",
     170000, 235000, "$170K–$235K", "Apr 2026",
     "https://jobs.bd.com/search-jobs?k=internal%20audit",
     8.2,
     "Franklin Lakes HQ; medtech regulatory rigor maps to Yasir's pharma-style audit instincts. IT audit + AI is BD's growth area."),

    (2, "Insmed", "Director, Internal Audit", "—",
     "Biotech", "Bridgewater, NJ",
     175000, 245000, "$175K–$245K", "Apr 2026",
     "https://careers.insmed.com/jobs",
     8.1,
     "Mid-cap biotech IPO graduate; small audit team means strategic visibility. Bridgewater commute is 45 min from Newark."),

    (2, "BioNTech US", "Senior Director, Internal Audit", "—",
     "Biotech", "Berkeley Heights, NJ",
     185000, 260000, "$185K–$260K", "Mar 2026",
     "https://careers.biontech.com/global/en/search-results?keywords=internal%20audit",
     8.0,
     "Building US internal audit from scratch — Yasir's program-build experience at Citi consent-order work is the differentiator."),

    (2, "RBC City National", "VP, Internal Audit", "—",
     "G-SIB-Adj Bank", "Jersey City, NJ",
     160000, 220000, "$160K–$220K", "May 2026",
     "https://jobs.rbc.com/ca/en/search-results?keywords=internal%20audit&locations=Jersey%20City",
     8.0,
     "Jersey City office, PATH from Newark. RBC's US private bank build-out needs audit talent that can engage federal banking regulators."),

    (2, "Panasonic North America", "Director, Internal Audit", "—",
     "Corporate", "Newark, NJ",
     160000, 225000, "$160K–$225K", "Apr 2026",
     "https://na.panasonic.com/us/about-us-panasonic/careers",
     8.0,
     "Walking distance to Newark Penn. Panasonic NA HQ is at 2 Riverfront Plaza — Yasir literally lives here."),

    (2, "ADP", "VP, Internal Audit", "—",
     "Corporate FinTech", "Roseland, NJ",
     180000, 250000, "$180K–$250K", "Apr 2026",
     "https://jobs.adp.com/search-jobs?ks=internal%20audit",
     7.9,
     "Roseland commute, FinTech payroll giant with serious AI/ML investment. ADP IA pays competitively for NJ corporate."),

    (2, "SMBC", "Director, Internal Audit", "—",
     "Bank", "Jersey City, NJ",
     170000, 230000, "$170K–$230K", "Mar 2026",
     "https://smbcgroup.wd1.myworkdayjobs.com/SMBC?q=internal%20audit",
     7.9,
     "Japanese megabank US arm at Newport JC tower. PATH-friendly; Yasir's Fed-examiner background plays well with foreign-bank-org oversight."),

    (2, "State Street", "VP, Audit Manager — AI Governance", "—",
     "G-SIB Bank", "New York, NY (Hybrid)",
     150000, 210000, "$150K–$210K", "Apr 2026",
     "https://careers.statestreet.com/global/en/search-results?keywords=AI%20audit",
     7.8,
     "Custody + asset-services AI risk lane. Hybrid; pay band sits below the other G-SIBs but title is portable."),

    (2, "Embecta", "Director, Internal Audit", "—",
     "Medtech", "Parsippany, NJ",
     160000, 220000, "$160K–$220K", "Mar 2026",
     "https://embecta.wd1.myworkdayjobs.com/Embecta?q=internal%20audit",
     7.8,
     "Recent BD spinoff still building IA function. Parsippany is 30 min from Newark; high impact, less brand prestige."),

    (2, "Otsuka America Pharmaceutical", "Director, Internal Audit", "—",
     "Corporate Pharma", "Princeton, NJ",
     170000, 235000, "$170K–$235K", "Apr 2026",
     "https://www.otsuka-us.com/careers",
     7.7,
     "Princeton commute. Otsuka US is publicly hiring audit + compliance after a string of GxP findings."),

    (2, "RSM US", "Director, Risk Consulting — AI Governance", "—",
     "Mid-Market Consulting", "Edison, NJ",
     175000, 245000, "$175K–$245K", "Apr 2026",
     "https://rsmus.com/careers/search-jobs.html?search=AI%20risk",
     7.7,
     "Mid-market consulting pays director-track well. Edison office; Yasir's AI Governance Professional path makes him a billing-rate asset."),

    (2, "TD Bank", "VP, Audit Manager — AI Risk", "—",
     "Bank", "Mt Laurel, NJ",
     160000, 210000, "$160K–$210K", "Mar 2026",
     "https://td.wd3.myworkdayjobs.com/TD?q=internal%20audit",
     7.6,
     "South Jersey commute (90 min) is the friction. But TD's post-AML-consent-order build is the right work."),

    (2, "Legend Biotech", "Director, Internal Audit", "—",
     "Biotech", "Somerset, NJ",
     165000, 225000, "$165K–$225K", "Mar 2026",
     "https://legendbiotech.wd5.myworkdayjobs.com/external?q=internal%20audit",
     7.6,
     "CAR-T biotech with rapid commercial growth. Small IA team = high leverage. Somerset is 45 min from Newark."),

    # ---------------- TIER 3 (6.5–7.4) — solid backups ----------------
    (3, "Princeton University", "Senior Auditor, Office of Audit & Compliance", "—",
     "Academic Admin", "Princeton, NJ",
     135000, 180000, "$135K–$180K", "Apr 2026",
     "https://main-princeton.icims.com/jobs/search?ss=1&searchKeyword=audit",
     7.4,
     "Stable, prestige employer; Yasir's DBA program credentials are a hiring asset. Hybrid possible."),

    (3, "NJIT", "Director, Internal Audit", "—",
     "Academic Admin", "Newark, NJ",
     140000, 185000, "$140K–$185K", "Mar 2026",
     "https://njit.csod.com/ux/ats/careersite/1/home?c=njit",
     7.3,
     "Walk to work from downtown Newark. Higher-ed audit is steady; salary trails industry but lifestyle wins."),

    (3, "Rutgers University", "Senior Internal Auditor", "—",
     "Academic Admin", "New Brunswick, NJ",
     125000, 170000, "$125K–$170K", "Apr 2026",
     "https://jobs.rutgers.edu/postings/search",
     7.2,
     "State school audit office, generous pension + tuition benefit. Salary band is a step down but covers DBA tuition reimbursement."),

    (3, "Avis Budget Group", "Director, Internal Audit", "—",
     "Corporate", "Parsippany, NJ",
     155000, 210000, "$155K–$210K", "Apr 2026",
     "https://jobs.avisbudgetgroup.com/search?q=internal%20audit",
     7.2,
     "Parsippany HQ. Avis IA team is small but covers global ops + treasury — Yasir's Treasury/CIO experience fits."),

    (3, "Seton Hall University", "Director, Internal Audit", "—",
     "Academic Admin", "South Orange, NJ",
     130000, 175000, "$130K–$175K", "Mar 2026",
     "https://jobs.shu.edu/",
     7.0,
     "South Orange, 20 min from Newark. Catholic university IA office; smaller, slower, stable."),

    (3, "Crowe LLP", "Senior Manager, Risk Consulting", "—",
     "Mid-Market Consulting", "Livingston, NJ",
     140000, 190000, "$140K–$190K", "Apr 2026",
     "https://www.crowe.com/careers/search-jobs",
     7.0,
     "Livingston is a 25-min drive. Crowe's FS practice is bigger than its brand suggests; AI risk advisory is hiring."),

    (3, "NRG Energy", "Director, Internal Audit", "—",
     "Energy", "Princeton, NJ",
     160000, 220000, "$160K–$220K", "Mar 2026",
     "https://www.nrg.com/careers.html",
     7.0,
     "Princeton commute. Energy-sector internal audit; NRG has serious AI/ML investment in trading ops."),

    (3, "Baker Tilly", "Senior Manager, Risk Advisory", "—",
     "Mid-Market Consulting", "Iselin, NJ",
     135000, 185000, "$135K–$185K", "Apr 2026",
     "https://bakertilly.com/careers/search-jobs",
     6.8,
     "Iselin office, easy commute. Pay trails Big 4; partner track for the right hire."),

    (3, "SOLV Energy", "Senior Audit Manager", "—",
     "Energy", "Edison, NJ",
     140000, 195000, "$140K–$195K", "Mar 2026",
     "https://solvenergy.com/careers/",
     6.7,
     "Renewables EPC contractor. Smaller IA team, but heavy on project-controls — adjacent to Yasir's program-management experience."),

    (3, "Robert Half (Mgmt Resources)", "Senior Audit Consultant — interim VP", "—",
     "Staffing", "Somerset, NJ",
     130000, 175000, "$130K–$175K", "May 2026",
     "https://www.roberthalf.com/us/en/jobs?keywords=audit",
     6.6,
     "Interim/contract bridge while permanent search runs. Often comes with extension or conversion offer."),

    (3, "Kearny Bank", "VP, Internal Audit", "—",
     "Community Bank", "Fairfield, NJ",
     130000, 180000, "$130K–$180K", "Mar 2026",
     "https://kearnybank.applicantpool.com/jobs/",
     6.5,
     "Small community bank IA leader role. Title good, comp light. Backup option if G-SIB search drags."),

    # ---------------- TIER 4 (<6.5) — adjunct / supplemental ----------------
    (4, "Stevens Institute of Technology", "Adjunct Faculty — FinTech & AI Audit", "—",
     "Academic-Adjunct", "Hoboken, NJ",
     0, 0, "$1,800/credit", "Apr 2026",
     "https://www.stevens.edu/about-stevens/work-at-stevens",
     6.2,
     "Hoboken evening adjunct; pairs with DBA timeline and AI governance positioning. Pure signaling/publication play."),

    (4, "FIU Online", "Adjunct Faculty — AI Ethics & Audit", "—",
     "Academic-Adjunct", "Remote / Miami, FL",
     0, 0, "$1,975/credit", "Apr 2026",
     "https://hr.fiu.edu/careers/",
     6.0,
     "FIU is Yasir's DBA institution — adjunct slot keeps the academic affiliation visible and pays the dissertation runway."),

    (4, "NJIT", "Adjunct Faculty — Risk Management", "—",
     "Academic-Adjunct", "Newark, NJ",
     0, 0, "$1,500/credit", "Mar 2026",
     "https://njit.csod.com/ux/ats/careersite/1/home?c=njit",
     5.8,
     "Walk-to-work adjunct slot. Tiny check but stacks teaching credential during the search."),

    (4, "Rider University", "Adjunct Faculty — Accounting & Audit", "—",
     "Academic-Adjunct", "Lawrenceville, NJ",
     0, 0, "$1,400/credit", "Mar 2026",
     "https://employment.rider.edu/postings/search",
     5.7,
     "Lawrenceville is a stretch commute but it's an evening-only slot. Backup teaching credential."),

    (4, "Saint Peter's University", "Adjunct Faculty — Auditing", "—",
     "Academic-Adjunct", "Jersey City, NJ",
     0, 0, "$1,400/credit", "Mar 2026",
     "https://saintpeters.peopleadmin.com/postings/search",
     5.7,
     "PATH-accessible; Jesuit university with growing business school. Small evening class."),

    (4, "Fairleigh Dickinson University", "Adjunct Faculty — Risk & Compliance", "—",
     "Academic-Adjunct", "Teaneck, NJ",
     0, 0, "$1,500/credit", "Mar 2026",
     "https://fdujobs.fdu.edu/postings/search",
     5.6,
     "Teaneck campus. Lower-pay but accepting adjuncts on rolling basis."),

    (4, "Kean University", "Adjunct Faculty — AI Ethics", "—",
     "Academic-Adjunct", "Union, NJ",
     0, 0, "$1,300/credit", "Mar 2026",
     "https://jobs.kean.edu/postings/search",
     5.6,
     "Union NJ commute. AI Ethics syllabus aligns with Yasir's dissertation."),

    (4, "New Jersey City University", "Adjunct Faculty — Risk Management", "—",
     "Academic-Adjunct", "Jersey City, NJ",
     0, 0, "$1,300/credit", "Mar 2026",
     "https://njcu.peopleadmin.com/postings/search",
     5.6,
     "Jersey City, walkable from PATH. NJCU is consistently hiring adjuncts in the business school."),

    (4, "Montclair State University", "Adjunct Faculty — Accounting", "—",
     "Academic-Adjunct", "Montclair, NJ",
     0, 0, "$1,400/credit", "Mar 2026",
     "https://montclair.peopleadmin.com/postings/search",
     5.5,
     "Montclair is 20 min from Newark. Solid backup teaching slot."),

    (4, "William Paterson University", "Adjunct Faculty — Business", "—",
     "Academic-Adjunct", "Wayne, NJ",
     0, 0, "$1,300/credit", "Feb 2026",
     "https://wpunj.peopleadmin.com/postings/search",
     5.5,
     "Wayne commute is long. Lowest-priority adjunct backup."),

    (4, "Mercer County Community College", "Adjunct Faculty — Business Audit", "—",
     "Academic-Adjunct", "Trenton, NJ",
     0, 0, "$1,200/credit", "Feb 2026",
     "https://www.mccc.edu/admin_hr_employment.shtml",
     5.5,
     "Community-college adjunct. Lowest comp but easiest qualification check."),

    (4, "Essex County College", "Adjunct Faculty — Business Management", "—",
     "Academic-Adjunct", "Newark, NJ",
     0, 0, "$1,100/credit", "Feb 2026",
     "https://www.essex.edu/hr/",
     5.5,
     "Walk-to-work adjunct in Newark. Stacks the teaching credential without commute cost."),
]
